# This is a basic workflow to help you get started with Actions

name: Convert md to html
on: [push, workflow_dispatch]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Export Slides HTML
        run: npx @marp-team/marp-cli@latest SLIDES.md -o pathlib-SoHotRightNow.html --html true

      - name: Export Slides PDF
        run: npx @marp-team/marp-cli@latest SLIDES.md -o pathlib-SoHotRightNow.pdf --html true

      - name: Print directory
        run: ls -a
      
      - name: Archive Exports
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: pathlib-SoHotRightNow.*
          retention-days: 7

      - name: Cut a release (main only)
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'main')
        with:
          artifacts: pathlib-SoHotRightNow.*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: Revision ${{ github.event.repository.updated_at }}
